{   ((1, 2048), 0, 'inductor_standalone'): {   'cache_key': 'au77g5zyoztb6k2tpjihfcmal7223esfr3r6ldvoirkaha2pkyih',
                                               'graph_handle': (   'artifact_compile_range_1_2048_subgraph_0',
                                                                   'E:\\OmniSpace\\.cache\\vllm\\torch_compile_cache\\49f2c9c22e\\rank_0_0\\backbone\\artifact_compile_range_1_2048_subgraph_0')},
    ((1, 2048), 1, 'inductor_standalone'): {   'cache_key': 'astfdf7wbmblxvb4upnytvugmuw4u7b3xapedm45ijsfezdeu3zm',
                                               'graph_handle': (   'artifact_compile_range_1_2048_subgraph_1',
                                                                   'E:\\OmniSpace\\.cache\\vllm\\torch_compile_cache\\49f2c9c22e\\rank_0_0\\backbone\\artifact_compile_range_1_2048_subgraph_1')},
    ((1, 2048), 2, 'inductor_standalone'): {   'cache_key': 'asju52bzt6xhehy6dmuporvciki3eiojsk6rksbvlwgiain5q7ps',
                                               'graph_handle': (   'artifact_compile_range_1_2048_subgraph_2',
                                                                   'E:\\OmniSpace\\.cache\\vllm\\torch_compile_cache\\49f2c9c22e\\rank_0_0\\backbone\\artifact_compile_range_1_2048_subgraph_2')},
    ((1, 2048), 4, 'inductor_standalone'): {   'cache_key': 'ajgunqtf3ko5pqq7usomxv6xyxnkydkeltnzvjuvfgva3dbk7tri',
                                               'graph_handle': (   'artifact_compile_range_1_2048_subgraph_4',
                                                                   'E:\\OmniSpace\\.cache\\vllm\\torch_compile_cache\\49f2c9c22e\\rank_0_0\\backbone\\artifact_compile_range_1_2048_subgraph_4')},
    ((1, 2048), 36, 'inductor_standalone'): {   'cache_key': 'arsveqjl5il42gbjpggyq7glkqbvv2eujl7al4vro22wvg6gzxz2',
                                                'graph_handle': (   'artifact_compile_range_1_2048_subgraph_36',
                                                                    'E:\\OmniSpace\\.cache\\vllm\\torch_compile_cache\\49f2c9c22e\\rank_0_0\\backbone\\artifact_compile_range_1_2048_subgraph_36')}}