# mypy 配置（批 4：编程语言规范合规·第四道防线）
# 用法见 tools/run_mypy.py；范围=backend + launcher（用户令 2026-09-04：
# packaging_console / license_console 代码冻结，不检）。
# 策略：先非 strict + 基线冻结（tools/mypy_baseline.txt，只增不减）——
# 存量报错不阻塞提交，新代码零容忍；strict 化随豁免递减另行立项。
[mypy]
python_version = 3.10
ignore_missing_imports = True
check_untyped_defs = True
no_warn_unused_configs = True
warn_redundant_casts = True
